# Generated by Django 6.0 on 2026-03-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=30)),
                ('goal_text', models.CharField(max_length=90)),
                ('goal_status', models.BooleanField(default=False)),
                ('goal_description', models.CharField(max_length=90)),
            ],
        ),
    ]
