# Generated by Django 6.0 on 2026-03-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_goal_options_remove_goal_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
