# Generated by Django 6.0 on 2026-04-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
